### ISSUE TITLE
how to use it using C# with .NET 4.5 framework

### ISSUE THREAD

**Issue by myalsailamy** [Grizley56/GoogleTranslateFreeApi#10]
could you give me example or simple code allow me to use it using .NET 4.5 framework because nothing work with me , but on core it work fine 

thank you ,,

**Comment by Grizley56** [comment]
Hello! Can you describe an issue?
If you get something like 
**"FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"** 
try to install Newtonsoft.Json package (version 10.0.*)

**Comment by myalsailamy** [comment]
I have already installed all the libraries and Run without errors .. but when I request a translation , nothing happens and the application screen freezes without any messages or any response .. Maybe it has to do with async and wait functions and 4.5 framework.

**Comment by myalsailamy** [comment]
thank ,, i found my problem here
https://stackoverflow.com/questions/36925852/c-sharp-getstringasync-never-returns-proper-way-of-doing-async-get
