### ISSUE TITLE
Way of skipping certain parts of the text from being translated?

### ISSUE THREAD

**Issue by KingSlendy** [Grizley56/GoogleTranslateFreeApi#12]
I tried using both:
`<span translate="no">Part of text</span>`
`<span class="notranslate">Part of text</span>`
But none seemed to work, so this left me wondering if there was a way of achieving this?

**Comment by Grizley56** [comment]
You could try to parse html text to DOM and translate only text nodes.  See [htmlagilitypack](https://github.com/zzzprojects/html-agility-pack)

**Comment by KingSlendy** [comment]
I ended up using a different method but thanks anyway! :D
