### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sargis-tovmasyan** [Grizley56/GoogleTranslateFreeApi#13]
As I understand google changed its API (or link) and this nuget now is obsolete, check it, please.

**Comment by drony** [comment]
it's work

**Comment by Grizley56** [comment]
@Saqo1995s describe your problem please

**Comment by freiend** [comment]
Doesn't work for me also. I'm trying to make it work in Unity3d project.
assembly.GetManifestResourceStream("GoogleTranslateFreeApi.Languages.json")  returns null

EDIT: Ok, it's my own fault that I couldn't figure out how to read Languages.json. I ended up editing script to work without it. I needed only 2 languages after all. So it works ok, returns all meanings/synonyms just as I needed. Thanks!
