### ISSUE TITLE
System.NotSupportedException: 'The method is no longer valid, or something went wrong'

### ISSUE THREAD

**Issue by JKamsker** [Grizley56/GoogleTranslateFreeApi#20]
Translating from German to English:
```
var from = Language.German;
var to = Language.English;

var result = await _translator.TranslateLiteAsync(text, from, to);
```

**Comment by cbayerlein** [comment]
Same here :(

**Comment by mnxamoto** [comment]
Same here

**Comment by zhmxiaowo** [comment]
same here

**Comment by JKamsker** [comment]
I eventually got it working but google eventually blocks requests after a certain amount of time.

You guys are really better off using the translator of azure or similar. It has a tier where you can translate thousands of words for free.

**Comment by Mayron** [comment]
@JKamsker Not very useful to tell us you got it working without any details.

Getting the same error and no solution has been provided yet.
