### ISSUE TITLE
Free?

### ISSUE THREAD

**Issue by Lelelo1** [Grizley56/GoogleTranslateFreeApi#21]
How can this be free when google translate is not free?

**Comment by sanslash332** [comment]
@Lelelo1  simply, working against the same secret api that the google translate web service uses.

Or, using a crawler on the google translate website, bot methods can work, but you have to stai alert on to any non announsed changes on the api, or the website itself.

But, at least that I know, this awesome api doesn't work sinze 2019.

**Comment by Lelelo1** [comment]
Ok, thanks for the reply

**Comment by sanslash332** [comment]
@Lelelo1 if you want to try this library, try one of the forks. One was updated on january of this year, and aparently is still working.
