### ISSUE TITLE
Can I translate the text "html" page? 

### ISSUE THREAD

**Issue by it19862** [Grizley56/GoogleTranslateFreeApi#3]
I have a "html" code page.
The page contains the text in "English".

Can the program "GoogleTranslateFreeApi" translate the text of the page into another language so that I get the "html" code of the page with the text in another language?
If this is not possible, could you give recommendations on how this can be implemented?

**Comment by Grizley56** [comment]
Unfortunately, it's not possible for this library. I cant give an advice, but probably you can achieve this after analyzing the html document, and translate required nodes. I think there is suitable libraries for this requirement
