### ISSUE TITLE
How can I get statistics on the limit used by the Google Translator?

### ISSUE THREAD

**Issue by it19862** [Grizley56/GoogleTranslateFreeApi#4]
Google Translator has text translation restrictions.

If I exceed the limit of restrictions, the "GoogleTranslateFreeApi" may issue a message that I have exceeded the limit?
If this is not possible, can you give recommendations on how this can be implemented?

**Comment by Grizley56** [comment]
You mean the restriction of maximum symbols per translate or maximum count of requests before getting a ban?

**Comment by it19862** [comment]
@Grizley56   
I do not remember exactly what the restrictions are, because I did not understand this issue.


I mean, are there any restrictions:
 - to translate the total number of characters;
 - to translate the number of characters per minute;
 - to translate the number of characters per hour;
 - to translate the number of characters per day;
other restrictions.

Could you add a message to "GoogleTranslateFreeApi" if the limits are exceeded or the statistics panel where it will display how much limit is spent and how much is left.

If you have this opportunity

**Comment by Grizley56** [comment]
@it19862 
I'm not sure that there is any way to get such sort of information. But i can say with confidence: you will get a ban for a few hours (give or take) after some count of requests.

> P.S you can use a proxy to avoid a block.

_BramscoChill_ has tried to circumvent the system, using cookies and interval between requests. Perhaps it will help you: [BramscoChill/GoogleTranslateFreeApi](https://github.com/BramscoChill/GoogleTranslateFreeApi)
By the other hand, you can use the official google-translate-api.
[https://cloud.google.com/translate/pricing](https://cloud.google.com/translate/pricing)
It's not for free ($20 per 1,000,000 characters*), but you wont get a ban, and probably you will get the requred statistic.
