### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by sanslash332** [Grizley56/GoogleTranslateFreeApi#6]
Hello!

Currently exist a nuget package for the lib? Or if not exist plans to upload it as a package? :)

thanks! Is very awesome!

**Comment by Grizley56** [comment]
Hello!

No, there is no nuget integration with this library, but probably i'll publish it soon.

Thank you for the suggestion!

**Comment by sanslash332** [comment]
OK, thanks!

 

I tested it and is awesome!

 

Currently I added it as a git submodule to my repository and works like a charm!

 

:)

 

Thanks.
