### ISSUE TITLE
Can not convert Null to Double

### ISSUE THREAD

**Issue by fx2xf** [Grizley56/GoogleTranslateFreeApi#8]
I keep getting this exception when I send large texts to translate
I get it randomly and I can't really predict when it's thrown
this is the stack trace and I send the text I am sending as well

**at** Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
**at** GoogleTranslateFreeApi.GoogleTranslator.GetTranslationCorrections(JToken response)
**at** GoogleTranslateFreeApi.GoogleTranslator.ResponseToTranslateResultParse(String result, String sourceText, Language sourceLanguage, Language targetLanguage, Boolean additionInfo)
 **at** GoogleTranslateFreeApi.GoogleTranslator.GetTranslationResultAsync(String originalText, Language fromLanguage, Language toLanguage, Boolean additionInfo) at GoogleTranslateFreeApi.GoogleTranslator.TranslateLiteAsync(String originalText, Language fromLanguage, Language toLanguage)
**at** FreeTranslatorApiRest.Controllers.TranslateController.TranslateLongText(TranslationObject translationObject, String targetLang, String sourceLang) in {MyWorkSpace}\\TranslateController.cs:line 142"

the text I am sending :
[sample.txt](https://github.com/Grizley56/GoogleTranslateFreeApi/files/3367057/sample.txt)

**Comment by Grizley56** [comment]
Thanks for an issue, will fix it
